export const data = [
    //GiftCards
    {
        id: 1,
        titulo: "GIFT CARD 50 SOLES",
        costo: 50,
        imagen: "/Images/rex-removebg-preview.png",
        cantidad: 1,
    },
    {
        id: 2,
        titulo: "GIFT CARD 100 SOLES",
        costo: 100,
        imagen: "/Images/rex-removebg-preview.png",
        cantidad: 1,
    },
    {
        id: 3,
        titulo: "GIFT CARD 150 SOLES",
        costo: 150,
        imagen: "/Images/rex-removebg-preview.png",
        cantidad: 1,
    },
    //Promociones
    {
        id: 4,
        costo: 120,
        imagen: "/Images/Promos/Promo1.jpg",
        titulo: "Pack Familiar 4 personas",
        descripcion:
            "ceviche de pescado + arroz con mariscos + jalea mixta + jarra de chicha.",
        cantidad: 1,
    },
    {
        id: 5,
        costo: 170,
        imagen: "/Images/Promos/Promo2.jpg",
        titulo: "Pack familiar 5 personas",
        descripcion:
            "Ceviche De Pescado + Arroz Con Mariscos + Parihuela Especial + Jalea Mixta + 1 Jarra de Chicha + 1 Leche De Tigre",
        cantidad: 1,
    },
    {
        id: 6,
        costo: 100,
        imagen: "/Images/Promos/Promo3.jpg",
        titulo: "PROMOCIÓN 1",
        descripcion:
            "2 Ceviches de pescado + Chicharrón de pescado + arroz con mariscos + jarra de chicha.",
        cantidad: 1,
    },
    {
        id: 7,
        costo: 100,
        imagen: "/Images/Promos/Promo4.jpg",
        titulo: "PROMOCIÓN 2",
        descripcion:
            "ceviche de pescado + chicharrón de pescado + chaufa de mariscos + causa de cangrejo + jarra de chicha.",
        cantidad: 1,
    },
    {
        id: 8,
        costo: 240,
        imagen: "/Images/Promos/Promo5.jpg",
        titulo: "Pack Familiar 8 personas",
        descripcion:
            "ceviche de pescado + arroz con mariscos + cabrilla frita + jalea mixta + causa richards + ceviche mixto + jarra de chicha y leche de tigre.",
        cantidad: 1,
    },
    //Aguaditos
    {
        id: 9,
        costo: 52,
        imagen: "/Images/Aguaditos/aguadito1.jpg",
        titulo: "CHUPE DE LANGOSTINO",
        cantidad: 1,
    },
    {
        id: 10,
        costo: 45,
        imagen: "/Images/Aguaditos/aguadito2.jpg",
        titulo: "AGUADITO DE PESCADO",
        cantidad: 1,
    },
    {
        id: 11,
        costo: 51,
        imagen: "/Images/Aguaditos/aguadito3.jpg",
        titulo: "PARIHUELA ESPECIAL",
        cantidad: 1,
    },
    {
        id: 12,
        costo: 77,
        imagen: "/Images/Aguaditos/aguadito4.jpg",
        titulo: "SUDADO DE CHITA",
        cantidad: 1,
    },
    {
        id: 13,
        costo: 60,
        imagen: "/Images/Aguaditos/aguadito5.jpg",
        titulo: "CHUPIN DE TRAMBOYO",
        cantidad: 1,
    },
    //Arroces
    {
        id: 14,
        costo: 53,
        imagen: "/Images/Arroces/arroz1.jpg",
        titulo: "CHAUFA RICHARDS",
        cantidad: 1,
    },
    {
        id: 15,
        costo: 52,
        imagen: "/Images/Arroces/arroz2.jpg",
        titulo: "ARROZ MARINERO C/PESCADO Y LANGOSTINO",
        cantidad: 1,
    },
    {
        id: 16,
        costo: 50,
        imagen: "/Images/Arroces/arroz3.jpg",
        titulo: "VOLCAN DE MARISCOS",
        cantidad: 1,
    },
    {
        id: 17,
        costo: 55,
        imagen: "/Images/Arroces/arroz4.jpg",
        titulo: "AEROPUERTO MAR Y TIERRALOMO FINO Y LANGOSTINO",
        cantidad: 1,
    },
    //Bebidas
    {
        id: 18,
        costo: 20,
        imagen: "/Images/Bebidas/bebidas1.jpg",
        titulo: "JARRA DE CHICHA",
        cantidad: 1,
    },
    {
        id: 19,
        costo: 20,
        imagen: "/Images/Bebidas/bebidas2.jpg",
        titulo: "JARRA DE LIMONADA",
        cantidad: 1,
    },
    {
        id: 20,
        costo: 20,
        imagen: "/Images/Bebidas/bebidas3.jpg",
        titulo: "JARRA DE MARACUYÁ",
        cantidad: 1,
    },
    {
        id: 21,
        costo: 6,
        imagen: "/Images/Bebidas/bebidas4.jpg",
        titulo: "Coca Cola 500ml",
        cantidad: 1,
    },
    {
        id: 22,
        costo: 6,
        imagen: "/Images/Bebidas/bebidas5.jpg",
        titulo: "Inca Cola 500ml",
        cantidad: 1,
    },
    {
        id: 23,
        costo: 6,
        imagen: "/Images/Bebidas/bebidas6.jpg",
        titulo: "Coca Cola sin azúcar 500ml",
        cantidad: 1,
    },
    {
        id: 24,
        costo: 6,
        imagen: "/Images/Bebidas/bebidas7.jpg",
        titulo: "Inca Kola sin azúcar 500ml",
        cantidad: 1,
    },
    {
        id: 25,
        costo: 6,
        imagen: "/Images/Bebidas/bebidas8.jpg",
        titulo: "Agua San Mateo sin gas 600ml",
        cantidad: 1,
    },
    {
        id: 26,
        costo: 6,
        imagen: "/Images/Bebidas/bebidas9.jpg",
        titulo: "Agua San Mateo con gas 600ml",
        cantidad: 1,
    },
    //Ceviches
    {
        id: 27,
        costo: 72,
        imagen: "/Images/Ceviches/ceviche1.jpg",
        titulo: "TRIO DE CEVICHES",
        cantidad: 1,
    },
    {
        id: 28,
        costo: 62,
        imagen: "/Images/Ceviches/ceviche2.jpg",
        titulo: "CEVICHE DE CONCHAS NEGRAS",
        cantidad: 1,
    },
    {
        id: 29,
        costo: 62,
        imagen: "/Images/Ceviches/ceviche3.jpg",
        titulo: "CEVICHE CLÁSICO MIXTO",
        cantidad: 1,
    },
    {
        id: 30,
        costo: 54,
        imagen: "/Images/Ceviches/ceviche4.jpg",
        titulo: "CEVICHE RICHARDS",
        cantidad: 1,
    },
    {
        id: 31,
        costo: 62,
        imagen: "/Images/Ceviches/ceviche5.jpg",
        titulo: "CEVICHE AFRODISIACO",
        cantidad: 1,
    },
    {
        id: 32,
        costo: 69,
        imagen: "/Images/Ceviches/ceviche6.jpg",
        titulo: "PIQUEO FRIO CON CAUSA",
        cantidad: 1,
    },
    //Chita
    {
        id: 33,
        costo: 75,
        imagen: "/Images/Chita/chita1.jpg",
        titulo: "CHITA CEVICHERA",
        cantidad: 1,
    },
    {
        id: 34,
        costo: 80,
        imagen: "/Images/Chita/chita2.jpg",
        titulo: "CHITA ENTERA AL AJOCROCANTE",
        cantidad: 1,
    },
    {
        id: 35,
        costo: 80,
        imagen: "/Images/Chita/chita3.jpg",
        titulo: "CHITA A LA CHORRILLANA",
        cantidad: 1,
    },
    {
        id: 36,
        costo: 90,
        imagen: "/Images/Chita/chita4.jpg",
        titulo: "CHITA ENTERA CON PICANTEDE CAMARONES",
        cantidad: 1,
    },
    {
        id: 37,
        costo: 80,
        imagen: "/Images/Chita/chita5.jpg",
        titulo: "CHITA ENTERA A LA MENIERE",
        cantidad: 1,
    },
    {
        id: 38,
        costo: 80,
        imagen: "/Images/Chita/chita6.jpg",
        titulo: "CHITA ENTERA EN SALSA DECALAMARES",
        cantidad: 1,
    },
    {
        id: 39,
        costo: 90,
        imagen: "/Images/Chita/chita7.jpg",
        titulo: "CHITA A LA MACHO",
        cantidad: 1,
    },
    //Entradas
    {
        id: 40,
        costo: 90,
        imagen: "/Images/Entradas/entrada1.jpg",
        titulo: "CAUSA FUSION CON LOMO FINO",
        cantidad: 1,
    },
    {
        id: 41,
        costo: 90,
        imagen: "/Images/Entradas/entrada2.jpg",
        titulo: "BROCHETAS DE PESCADO",
        cantidad: 1,
    },
    {
        id: 42,
        costo: 90,
        imagen: "/Images/Entradas/entrada3.jpg",
        titulo: "CAUSA A LA CHORRILLANACON FINOS TROZOS DE PESCADO",
        cantidad: 1,
    },
    {
        id: 43,
        costo: 90,
        imagen: "/Images/Entradas/entrada4.jpg",
        titulo: "CAUSA ROMANCE MARINO",
        cantidad: 1,
    },
    {
        id: 44,
        costo: 90,
        imagen: "/Images/Entradas/entrada5.jpg",
        titulo: "CAUSA POSEIDÓN",
        cantidad: 1,
    },
    {
        id: 45,
        costo: 90,
        imagen: "/Images/Entradas/entrada6.jpg",
        titulo: "LECHE DE TIGRE RICHARDS",
        cantidad: 1,
    },
    {
        id: 46,
        costo: 90,
        imagen: "/Images/Entradas/entrada7.jpg",
        titulo: "CAUSA RICHARDS CON LANGOSTINOS, PULPO Y PULPA DE CANGREJO",
        cantidad: 1,
    },
    //Jaleas
    {
        id: 47,
        costo: 63,
        imagen: "/Images/Jaleas/jaleas1.jpg",
        titulo: "CHICHARRON DE LANGOSTINOS",
        cantidad: 1,
    },
    {
        id: 48,
        costo: 55,
        imagen: "/Images/Jaleas/jaleas2.jpg",
        titulo: "CHICHARRON DE CALAMAR",
        cantidad: 1,
    },
    {
        id: 49,
        costo: 67,
        imagen: "/Images/Jaleas/jaleas3.jpg",
        titulo: "JALEA RICHARDS",
        cantidad: 1,
    },
    {
        id: 50,
        costo: 55,
        imagen: "/Images/Jaleas/jaleas4.jpg",
        titulo: "JALEA REAL",
        cantidad: 1,
    },
    {
        id: 51,
        costo: 58,
        imagen: "/Images/Jaleas/jaleas5.jpg",
        titulo: "JALEA EMPRESARIAL",
        cantidad: 1,
    },
    {
        id: 52,
        costo: 59,
        imagen: "/Images/Jaleas/jaleas6.jpg",
        titulo: "JALEA ASESINA",
        cantidad: 1,
    },
    {
        id: 53,
        costo: 85,
        imagen: "/Images/Jaleas/jaleas7.jpg",
        titulo: "JALEA PIURANA",
        cantidad: 1,
    },
    //Lenguado
    {
        id: 54,
        costo: 69,
        imagen: "/Images/Lenguado/lenguado1.jpg",
        titulo: "CEVICHE LENGUADO",
        cantidad: 1,
    },
    {
        id: 55,
        costo: 71,
        imagen: "/Images/Lenguado/lenguado2.jpg",
        titulo: "CEVICHE LENGUADO PULPO LANGOSTINO",
        cantidad: 1,
    },
    {
        id: 56,
        costo: 69,
        imagen: "/Images/Lenguado/lenguado3.jpg",
        titulo: "LENGUADO A LA HAWAIANA",
        cantidad: 1,
    },
    {
        id: 57,
        costo: 69,
        imagen: "/Images/Lenguado/lenguado4.jpg",
        titulo: "LENGUADO EN SALSA DE CHAMPINONES",
        cantidad: 1,
    },
    {
        id: 58,
        costo: 69,
        imagen: "/Images/Lenguado/lenguado5.jpg",
        titulo: "LENGUADO A LA FLORENTINA",
        cantidad: 1,
    },
    {
        id: 59,
        costo: 69,
        imagen: "/Images/Lenguado/lenguado6.jpg",
        titulo: "LENGUADO A LA ORIENTAL",
        cantidad: 1,
    },
    {
        id: 60,
        costo: 80,
        imagen: "/Images/Lenguado/lenguado7.jpg",
        titulo: "LENGUADO ENTERO EN CREMA AL AJO O HOJUELAS DE AJO CROCANTES",
        cantidad: 1,
    },
    {
        id: 61,
        costo: 80,
        imagen: "/Images/Lenguado/lenguado8.jpg",
        titulo: "lENGUADO ENTERO A LA MENIERE",
        cantidad: 1,
    },
    {
        id: 62,
        costo: 80,
        imagen: "/Images/Lenguado/lenguado9.jpg",
        titulo: "LENGUADO ENTERO A LA CHORRILLANA",
        cantidad: 1,
    },
    {
        id: 63,
        costo: 94,
        imagen: "/Images/Lenguado/lenguado10.jpg",
        titulo: "LENGUADO ENTERO C/ARROZ A LA CHICLAYANA",
        cantidad: 1,
    },
    {
        id: 64,
        costo: 85,
        imagen: "/Images/Lenguado/lenguado11.jpg",
        titulo: "LENGUAGO A LO MACHO",
        cantidad: 1,
    },
    //Pastas
    {
        id: 65,
        costo: 60,
        imagen: "/Images/Pastas/pasta1.jpg",
        titulo: "FETUCCINI A LA HUANCAíNA CONLOMO SALTADO (LOMO FINO)",
        cantidad: 1,
    },
    {
        id: 66,
        costo: 48,
        imagen: "/Images/Pastas/pasta2.jpg",
        titulo: "FETUCCINI AL PESTO CONPECHUGA A LA PLANCHA",
        cantidad: 1,
    },
    {
        id: 67,
        costo: 53,
        imagen: "/Images/Pastas/pasta3.jpg",
        titulo: "FETUCCINI A LA GORDON BLUEDE PESCADO",
        cantidad: 1,
    },
    //PescadoFrito
    {
        id: 68,
        costo: 51,
        imagen: "/Images/PescadoFrito/pescadofrito1.jpg",
        titulo: "CABRILLA FRITA",
        cantidad: 1,
    },
    {
        id: 69,
        costo: 46,
        imagen: "/Images/PescadoFrito/pescadofrito2.jpg",
        titulo: "TRUCHA A LA PARRILLA",
        cantidad: 1,
    },
    //PlatosCriollos
    {
        id: 70,
        costo: 54,
        imagen: "/Images/PlatosCriollos/platoscriollos1.jpg",
        titulo: "LOMO SALTADO",
        cantidad: 1,
    },
    {
        id: 71,
        costo: 60,
        imagen: "/Images/PlatosCriollos/platoscriollos2.jpg",
        titulo: "PARRILLA MARINA",
        cantidad: 1,
    },
    {
        id: 72,
        costo: 60,
        imagen: "/Images/PlatosCriollos/platoscriollos3.jpg",
        titulo:
            "RISOTO FUSIÓN C/ CHAMPIÑONESO LANGOSTINOS Y LOMO FINO A LA PARRILLA",
        cantidad: 1,
    },
    {
        id: 73,
        costo: 54,
        imagen: "/Images/PlatosCriollos/platoscriollos4.jpg",
        titulo: "LOMO FINO A LA PARRILLA",
        cantidad: 1,
    },
    {
        id: 74,
        costo: 78,
        imagen: "/Images/PlatosCriollos/platoscriollos5.jpg",
        titulo: "CORVINA A LA PLANCHA CONTACU TACU EN PICANTE DE MARISCO",
        cantidad: 1,
    },
    //TacuTacus
    {
        id: 75,
        costo: 85,
        imagen: "/Images/TacuTacus/tacutacu1.jpg",
        titulo: "TACU TACU CON HUEVERA FRITA",
        cantidad: 1,
    },
    {
        id: 76,
        costo: 85,
        imagen: "/Images/TacuTacus/tacutacu2.jpg",
        titulo: "TACU TACU EN AJí DE LANGOSTINOs",
        cantidad: 1,
    },
    {
        id: 77,
        costo: 85,
        imagen: "/Images/TacuTacus/tacutacu3.jpg",
        titulo: "TACU TACU RICHARDS",
        cantidad: 1,
    },
    {
        id: 78,
        costo: 85,
        imagen: "/Images/TacuTacus/tacutacu4.jpg",
        titulo: "TACU TACU CON PICANTE DECONCHAS NEGRAS",
        cantidad: 1,
    },
    //Tiraditos
    {
        id: 79,
        costo: 85,
        imagen: "/Images/Tiraditos/tiraditos1.jpg",
        titulo: "TIRADITO ENCUENTRO DE MAR",
        cantidad: 1,
    },
    {
        id: 80,
        costo: 85,
        imagen: "/Images/Tiraditos/tiraditos2.jpg",
        titulo: "TIRADITO DE POKER 4 ACES",
        cantidad: 1,
    },
    {
        id: 81,
        costo: 85,
        imagen: "/Images/Tiraditos/tiraditos3.jpg",
        titulo: "TIRADITO REY PELE",
        cantidad: 1,
    },
];
